from __future__ import annotations

from collections.abc import Callable
from typing import Any

from fastmcp import FastMCP

from aegis_alpha.adapters.factory import create_market_data_adapter
from aegis_alpha.models import AgentReviewCorrection, CandidateOutcomeReview
from aegis_alpha.runner import status_payload
from aegis_alpha.storage import AegisAlphaStore


mcp = FastMCP("aegis-alpha")


def _call_tool(callback: Callable[[Any], Any]) -> Any:
    try:
        adapter = create_market_data_adapter()
        return callback(adapter)
    except Exception as exc:
        return {
            "data_mode": "unavailable",
            "error_type": type(exc).__name__,
            "error": str(exc),
            "disclaimer": "Data source unavailable. Research output only; do not infer missing market data.",
        }


def _call_store(callback: Callable[[AegisAlphaStore], Any]) -> Any:
    try:
        return callback(AegisAlphaStore())
    except Exception as exc:
        return {
            "data_mode": "unavailable",
            "error_type": type(exc).__name__,
            "error": str(exc),
            "disclaimer": "Data source unavailable. Research output only; do not infer missing market data.",
        }


@mcp.tool
def get_market_snapshot() -> dict:
    """Return a read-only A-share market sentiment snapshot."""
    return _call_tool(lambda adapter: adapter.get_market_snapshot().model_dump())


@mcp.tool
def get_market_sentiment_gate() -> dict:
    """Return the board-chasing market sentiment gate."""
    return _call_tool(lambda adapter: adapter.get_market_sentiment_gate().model_dump())


@mcp.tool
def get_limitup_pool() -> list[dict]:
    """Return the current limit-up pool."""
    return _call_tool(lambda adapter: [item.model_dump() for item in adapter.get_limitup_pool()])


@mcp.tool
def get_break_board_pool() -> list[dict]:
    """Return the current break-board pool."""
    return _call_tool(lambda adapter: [item.model_dump() for item in adapter.get_break_board_pool()])


@mcp.tool
def get_stock_realtime_snapshot(symbol: str) -> dict:
    """Return a read-only realtime or latest provider snapshot for one stock."""
    return _call_tool(lambda adapter: adapter.get_stock_realtime_snapshot(symbol).model_dump())


@mcp.tool
def get_stock_orderbook_snapshot(symbol: str) -> dict:
    """Return a read-only orderbook summary for one stock when the provider supports it."""
    return _call_tool(lambda adapter: adapter.get_stock_orderbook_snapshot(symbol).model_dump())


@mcp.tool
def get_stock_minute_replay_snapshot(symbol: str, end_day: str = "", limit_days: int = 1) -> dict:
    """Return read-only jvQuant minute replay data and Aegis-calculated speed windows."""
    safe_limit = max(1, min(int(limit_days or 1), 30))
    safe_end_day = end_day.strip() or None
    return _call_tool(
        lambda adapter: adapter.get_stock_minute_replay_snapshot(symbol, safe_end_day, safe_limit).model_dump()
    )


@mcp.tool
def get_recent_market_events(limit: int = 20, event_type: str = "") -> list[dict]:
    """Return recent structured market events generated by Aegis Alpha signal rules."""
    safe_limit = max(1, min(int(limit or 20), 100))
    safe_event_type = event_type.strip() or None
    return _call_tool(
        lambda adapter: [
            event.model_dump()
            for event in adapter.get_recent_market_events(safe_limit, safe_event_type)
        ]
    )


@mcp.tool
def get_signal_snapshot(symbol: str) -> dict:
    """Return the latest structured signal snapshot for one stock."""
    return _call_tool(lambda adapter: adapter.get_signal_snapshot(symbol).model_dump())


@mcp.tool
def get_event_scoring_config() -> dict:
    """Return the active event scoring configuration without secrets."""
    return _call_tool(lambda adapter: adapter.get_event_scoring_config().model_dump())


@mcp.tool
def get_realtime_connection_status() -> dict:
    """Return realtime provider connection state without starting a raw stream."""
    return _call_tool(lambda adapter: adapter.get_realtime_connection_status().model_dump())


@mcp.tool
def get_runner_status() -> dict:
    """Return launchd-managed runner status from the local status file."""
    try:
        return status_payload()
    except Exception as exc:
        return {
            "state": "STOPPED",
            "error_type": type(exc).__name__,
            "error": str(exc),
            "disclaimer": "Runner status unavailable. Do not infer live market state.",
        }


@mcp.tool
def explain_market_event(event_id: str) -> dict:
    """Explain a structured market event without issuing buy or sell instructions."""
    return _call_tool(lambda adapter: adapter.explain_market_event(event_id))


@mcp.tool
def review_candidate_outcome(symbol: str, trading_day: str) -> dict:
    """Return the stored or provider-derived review outcome for a candidate and trading day."""
    return _call_tool(lambda adapter: adapter.review_candidate_outcome(symbol, trading_day).model_dump())


@mcp.tool
def record_candidate_outcome(
    symbol: str,
    trading_day: str,
    touched_limit_up: bool | None = None,
    sealed_second_board: bool | None = None,
    broke_after_seal: bool | None = None,
    next_day_open_pct: float | None = None,
    next_day_high_pct: float | None = None,
    third_day_premium_pct: float | None = None,
    user_correction: str = "",
    notes: str = "",
) -> dict:
    """Store a read-only review/correction record for later strategy and skill tuning."""
    review = CandidateOutcomeReview(
        symbol=symbol,
        trading_day=trading_day,
        touched_limit_up=touched_limit_up,
        sealed_second_board=sealed_second_board,
        broke_after_seal=broke_after_seal,
        next_day_open_pct=next_day_open_pct,
        next_day_high_pct=next_day_high_pct,
        third_day_premium_pct=third_day_premium_pct,
        user_correction=user_correction,
        notes=[item.strip() for item in notes.split("|") if item.strip()],
    )
    return _call_tool(lambda adapter: adapter.record_candidate_outcome(review).model_dump())


@mcp.tool
def get_recent_agent_reviews(limit: int = 10) -> list[dict] | dict:
    """Return recently stored agent review results for chat-based correction."""
    safe_limit = max(1, min(int(limit or 10), 50))
    return _call_store(lambda store: [review.model_dump() for review in store.recent_agent_reviews(safe_limit)])


@mcp.tool
def record_agent_review_correction(
    review_id: str,
    symbol: str = "",
    correction_type: str = "OTHER",
    expected_grade: str = "",
    comment: str = "",
) -> dict:
    """Store a user correction about an agent review for later memory, skill, or scoring updates."""

    def _record(store: AegisAlphaStore) -> dict:
        normalized_type = correction_type.strip().upper() or "OTHER"
        normalized_grade = expected_grade.strip().upper() or None
        correction = AgentReviewCorrection(
            review_id=review_id.strip(),
            symbol=symbol.strip(),
            correction_type=normalized_type,
            expected_grade=normalized_grade,
            comment=comment.strip(),
        )
        saved = store.save_agent_review_correction(correction)
        summary = store.agent_correction_summary(limit=100)
        proposals = store.save_correction_action_proposals(summary)
        return {
            "correction": saved.model_dump(),
            "summary": summary.model_dump(exclude={"recent_corrections"}),
            "proposals": [proposal.model_dump(exclude={"decisions"}) for proposal in proposals],
            "disclaimer": "Correction stored locally for review. Hermes memory or skill updates are suggested, not automatically applied.",
        }

    return _call_store(_record)


@mcp.tool
def get_agent_correction_summary(limit: int = 100) -> dict:
    """Return correction patterns and suggested Hermes memory or skill updates."""
    safe_limit = max(1, min(int(limit or 100), 200))
    return _call_store(lambda store: store.agent_correction_summary(safe_limit).model_dump())


@mcp.tool
def create_correction_action_proposals(limit: int = 100) -> dict:
    """Create or update human-reviewable proposals from current correction routing."""
    safe_limit = max(1, min(int(limit or 100), 200))

    def _create(store: AegisAlphaStore) -> dict:
        summary = store.agent_correction_summary(safe_limit)
        proposals = store.save_correction_action_proposals(summary)
        return {
            "created_or_updated": [proposal.model_dump(exclude={"decisions"}) for proposal in proposals],
            "count": len(proposals),
            "disclaimer": "Proposals are pending review. Aegis Alpha does not apply memory, skill, config, or adapter changes automatically.",
        }

    return _call_store(_create)


@mcp.tool
def get_pending_correction_actions(limit: int = 20) -> list[dict] | dict:
    """Return pending correction action proposals waiting for human review."""
    safe_limit = max(1, min(int(limit or 20), 100))
    return _call_store(
        lambda store: [proposal.model_dump() for proposal in store.pending_correction_action_proposals(safe_limit)]
    )


@mcp.tool
def record_correction_action_decision(
    proposal_id: str,
    decision: str,
    note: str = "",
    decided_by: str = "user",
) -> dict:
    """Record a human decision for a correction action proposal without applying code/config changes."""

    def _record(store: AegisAlphaStore) -> dict:
        proposal = store.record_correction_action_decision(
            proposal_id=proposal_id.strip(),
            decision=decision.strip(),
            note=note.strip(),
            decided_by=decided_by.strip() or "user",
        )
        return {
            "proposal": proposal.model_dump(),
            "disclaimer": "Decision recorded only. Applying memory, skill, config, or adapter changes remains a separate explicit step.",
        }

    return _call_store(_record)


@mcp.tool
def get_correction_action_history(limit: int = 20) -> list[dict] | dict:
    """Return correction action proposals and their decision history."""
    safe_limit = max(1, min(int(limit or 20), 100))
    return _call_store(lambda store: [proposal.model_dump() for proposal in store.correction_action_history(safe_limit)])


@mcp.tool
def get_stock_history_limitup_stats(symbol: str) -> dict:
    """Return mock historical limit-up success and next-day premium stats."""
    return _call_tool(lambda adapter: adapter.get_stock_history_limitup_stats(symbol).model_dump())


@mcp.tool
def get_theme_strength(symbol: str) -> dict:
    """Return mock theme strength for one stock."""
    return _call_tool(lambda adapter: adapter.get_theme_strength(symbol).model_dump())


@mcp.tool
def get_second_board_candidates() -> list[dict]:
    """Return mock candidates for the second-board radar."""
    return _call_tool(lambda adapter: [item.model_dump() for item in adapter.get_second_board_candidates()])


@mcp.tool
def get_second_board_candidates_compact(limit: int = 12) -> list[dict]:
    """Return compact second-board candidates without verbose evidence."""

    def _compact(adapter: Any) -> list[dict]:
        safe_limit = max(1, min(int(limit or 12), 50))
        items = []
        for candidate in adapter.get_second_board_candidates()[:safe_limit]:
            items.append(
                {
                    "symbol": candidate.symbol,
                    "name": candidate.name,
                    "data_mode": candidate.data_mode,
                    "provider": candidate.provider,
                    "theme": candidate.theme,
                    "current_change_pct": candidate.current_change_pct,
                    "auction_change_pct": candidate.auction_change_pct,
                    "auction_turnover_cny": candidate.auction_turnover_cny,
                    "auction_turnover_rate": candidate.auction_turnover_rate,
                    "one_min_speed_pct": candidate.one_min_speed_pct,
                    "three_min_speed_pct": candidate.three_min_speed_pct,
                    "five_min_speed_pct": candidate.five_min_speed_pct,
                    "five_min_speed_window": candidate.five_min_speed_window,
                    "five_min_speed_timestamp": candidate.five_min_speed_timestamp,
                    "minute_replay_timestamp": candidate.minute_replay_timestamp,
                    "minute_replay_trading_day": candidate.minute_replay_trading_day,
                    "minute_replay_bar_count": candidate.minute_replay_bar_count,
                    "ten_min_speed_pct": candidate.ten_min_speed_pct,
                    "big_order_net_inflow_ratio": candidate.big_order_net_inflow_ratio,
                    "first_limit_up_time": candidate.first_limit_up_time,
                    "final_seal_time": candidate.final_seal_time,
                    "seal_amount_cny": candidate.seal_amount_cny,
                    "max_seal_amount_cny": candidate.max_seal_amount_cny,
                    "seal_to_turnover_ratio": candidate.seal_to_turnover_ratio,
                    "break_board_count": candidate.break_board_count,
                    "reseal_count": candidate.reseal_count,
                    "concept_tags": candidate.concept_tags[:8],
                    "topic_tags": candidate.topic_tags[:8],
                    "same_theme_rising_count": candidate.same_theme_rising_count,
                    "orderbook_quality_score": candidate.orderbook_quality_score,
                    "estimated_seal_probability": candidate.estimated_seal_probability,
                    "grade": candidate.grade,
                    "grade_reason": candidate.grade_reason,
                    "data_quality_summary": {
                        key: {
                            "confidence": value.confidence,
                            "usable_for_grading": value.usable_for_grading,
                        }
                        for key, value in candidate.data_quality.items()
                    },
                }
            )
        return items

    return _call_tool(_compact)


@mcp.tool
def get_second_board_candidate_data_quality(symbol: str) -> dict:
    """Return compact data-quality evidence for one second-board candidate."""

    def _quality(adapter: Any) -> dict:
        normalized = symbol.strip().upper().split(".", 1)[0]
        for candidate in adapter.get_second_board_candidates():
            if candidate.symbol == symbol or candidate.symbol == normalized:
                return {
                    "symbol": candidate.symbol,
                    "name": candidate.name,
                    "data_mode": candidate.data_mode,
                    "provider": candidate.provider,
                    "data_quality": {
                        key: value.model_dump()
                        for key, value in candidate.data_quality.items()
                    },
                }
        return {
            "symbol": symbol,
            "data_mode": "unavailable",
            "error": "Candidate not found in current second-board pool.",
        }

    return _call_tool(_quality)


@mcp.tool
def explain_candidate(symbol: str) -> dict:
    """Explain a watchlist candidate without issuing buy or sell instructions."""
    return _call_tool(lambda adapter: adapter.explain_candidate(symbol).model_dump())


@mcp.tool
def explain_second_board_candidate(symbol: str) -> dict:
    """Explain a second-board candidate without issuing buy or sell instructions."""
    return _call_tool(lambda adapter: adapter.explain_second_board_candidate(symbol).model_dump())


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
